### ISSUE TITLE
nasdaq_exteral_data.csv fails to parse

### ISSUE THREAD

**Issue by agent00jackson** [Zdong104/FNSPID_Financial_News_Dataset#1]
I downloaded the following csv from huggingface:
nasdaq_exteral_data.csv

Loading the first thousand rows works, however I get a lot of parsing errors when loading the whole file with dask. Is it possible to upload a parquet file or upload the code that generated the csv for debugging? I do not see where it is generated in this repo.

**Comment by Zdong104** [comment]
That is some error met by others as well. I will try to upload another version without merging everything been merged. 
@IronWindow

**Comment by Zdong104** [comment]
I tried again like 2 minutes ago (Apr 03, 11:44 PM, 2024), and it works, pandas version is 2.0.3. We did not use dask within our development so we are not clear about the details. 
We will also upload smaller files of different parts of csv which could be easier to be use later. 

<img width="1561" alt="Screenshot 2024-04-03 at 11 43 24 PM" src="https://github.com/Zdong104/FNSPID_Financial_News_Dataset/assets/77849792/3c3688e9-810e-4153-afb2-ff071c14683b">

**Comment by agent00jackson** [comment]
I tried again with base pandas and was able to generate chunks with the following code, in case others stumble on this:
```py
import pandas as pd
from tqdm import tqdm

news_schema = {
    'Date': str,
    'Article_title': str,
    'Stock_symbol': str,
    'Url': str,
    'Publisher': str,
    'Author': str,
    'Article': str,
    'Lsa_summary': str,
    'Luhn_summary': str,
    'Textrank_summary': str,
    'Lexrank_summary': str,
}

chunksize = 10 ** 6
for i, chunk in enumerate(tqdm(pd.read_csv('nasdaq_exteral_data.csv', chunksize=chunksize, dtype=news_schema, parse_dates=['Date']))):
    chunk['Date'] = pd.to_datetime(chunk['Date']).dt.date
    chunk.to_parquet(f'chunks/{i}.parquet')
```
