### ISSUE TITLE
FNSPID History Length

### ISSUE THREAD

**Issue by deeepwin** [Zdong104/FNSPID_Financial_News_Dataset#3]
Great work! I have downloaded the dataset from Hugging Face, could load and inspect it, but see that for many symbols like ADBE or DRI the data ranges back to only 2015. You mention the data goes back to 1999 in your paper. Is this only for a few stocks or am I doing something wrong?

**Comment by mimugara** [comment]
Also, the newest data is to only 2020 (different that 2023, which is the reported date)

**Comment by Zdong104** [comment]
The data range is not fully aligned from 1999 to 2023 for all stocks, We are still trying to work on the data range and make more stock sentiment data available. I recently talked with Bloomberg Senior Software Engineer. They do provide the terminal and you can also buy it directly. price will be counted as kb. if you need contact you can email me and I can forward the details to you.
