### ISSUE TITLE
Are the stock prices in the repo forward-adjusted?

### ISSUE THREAD

**Issue by natlank** [Zdong104/FNSPID_Financial_News_Dataset#4]
Hi, thank you for your great work on this repository.

I want to make sure whether the stock prices are forward-adjusted. One stock data prices (like AAPL) seem not to be forward-adjusted (adjusted for splits). Could you confirm whether the other stock data in the repository is forward-adjusted?

Appreciate your clarification!
Best regards

**Comment by Zdong104** [comment]
We did not include the forward-adjusted for numerical price data. The data downloaded from Yahoo finance without further modification. 
Sorry for the late reply :(

**Comment by natlank** [comment]
Thank you bro
